[[redirects]]
  from = "/data/suites.json"
  to = "https://meek-salmiakki-e84eac.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"